// ------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool.
//
// 	Changes to this file may cause incorrect behavior and will be lost if
// 	the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
/// <summary>
/// List of all Unity Input Axes (from the InputManager) in the project.
/// </summary>
public static class InputAxes
{
	public const string Horizontal = "Horizontal";
	public const string Vertical = "Vertical";
	public const string MouseX = "Mouse X";
	public const string MouseY = "Mouse Y";
	public const string Inventory = "Inventory";
	public const string Take = "Take";
	public const string Care = "Care";
}