// ------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool.
//
// 	Changes to this file may cause incorrect behavior and will be lost if
// 	the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
/// <summary>
/// List of all Unity Layers (as masks) in the project.
/// </summary>
public static class LayerMasks
{
	public const int Default = 1;
	public const int TransparentFX = 2;
	public const int IgnoreRaycast = 4;
	public const int Water = 16;
	public const int UI = 32;
}
